# Generated by Django 4.2.16 on 2026-04-08 09:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(help_text='e.g. Studio, Suite, 2-BR', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('media', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apartment / Unit',
                'verbose_name_plural': 'Apartments / Units',
                'ordering': ['property', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('residence', 'Residence'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('office', 'Office / Co-working')], default='apartment', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('media', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'role': 'owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='properties.apartment')),
            ],
            options={
                'verbose_name': 'Available Date Range',
                'verbose_name_plural': 'Available Date Ranges',
                'ordering': ['start'],
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='properties.property'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property')),
                ('user', models.ForeignKey(limit_choices_to={'role__in': ['client', 'guest']}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner'], name='properties__owner_i_9e1ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type'], name='properties__type_f58a00_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_public'], name='properties__is_publ_373e00_idx'),
        ),
    ]
