# Generated by Django 4.2.16 on 2026-04-08 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, default='')),
                ('specialization', models.CharField(blank=True, default='', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_properties', models.ManyToManyField(blank=True, related_name='assigned_workers', to='properties.property')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Profile',
                'verbose_name_plural': 'Worker Profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkerSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workers.workerprofile')),
            ],
            options={
                'verbose_name': 'Worker Schedule',
                'verbose_name_plural': 'Worker Schedules',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('worker', 'day_of_week')},
            },
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
